### ISSUE TITLE
如何重置或者手动删除苗圃信息

### ISSUE THREAD

**Issue by Schwi-xgh** [Lotlab/FFXIV-Gardening-Tracker#1]
请问如何重置或者手动删除苗圃信息 种植完被别人收获 不小心护理了别人的苗圃 都会留下无法清楚的记录
被别人收获后我再次播种也无法覆盖前一次的记录会一直保留着

**Comment by jim-kirisame** [comment]
选中条目按del

**Comment by Schwi-xgh** [comment]
> 选中条目按del

感谢
